- hosts: el6
  remote_user: root
  tasks:
  - name:  CentOS6 system copy zabbix-agent rpm
    copy: src=/etc/ansible/zabbix/zabbix-agent/zabbix-agent-4.0.0-1.alpha1.el6.x86_64.rpm dest=/tmp/zabbix-agent-4.0.0-1.alpha1.el6.x86_64.rpm
  - name: yum install zabbix-agent
    shell: cd /tmp;yum -y localinstall zabbix-agent-4.*.rpm
  - name: rm zabbix-agent
    shell: cd /tmp;rm -rf zabbix-agent-4.*.rpm
  - name: configure Server IP
    shell: sed -i 's/Server=127.0.0.1/Server=192.168.58.58/' /etc/zabbix/zabbix_agentd.conf  
  - name: configure ServerActive IP
    shell: sed -i 's/ServerActive=127.0.0.1/ServerActive=192.168.58.58/' /etc/zabbix/zabbix_agentd.conf
  - name: configure HostMetadata
    shell: sed -i 's/# HostMetadata=/HostMetadata=el6/' /etc/zabbix/zabbix_agentd.conf
  - name: CentOS6 system configure Hostname
    shell: host=`hostname`;sed -i 's/Hostname=Zabbix server/Hostname='$host'/' /etc/zabbix/zabbix_agentd.conf
  - name:  Zabbix Script 
    file: name=/etc/zabbix/script state=directory
  - name: copy Script
    copy: src=/etc/ansible/zabbix/zabbix-script/zabbix_linux.sh dest=/etc/zabbix/script//zabbix_linux.sh
  - name: To grant authorization
    shell: chown -R zabbix.zabbix /etc/zabbix/script;chmod +x /etc/zabbix/script/zabbix_linux.sh
  - name: Copy config
    copy: src=/etc/ansible/zabbix/zabbix-script/zabbix_linux.conf dest=/etc/zabbix/zabbix_agentd.d/zabbix_linux.conf
  - name: CentOS6 system start zabbix
    shell: /etc/init.d/zabbix-agent start;chkconfig zabbix-agent on
